events {}

http {
    upstream reports-service {
        server reports-service:8080;
    }

    upstream attendance-service {
        server attendance-service:8080;
    }

    server {
        listen 80;

        location /reports/ {
            proxy_pass http://reports-service;
        }

        location /attendance/ {
            proxy_pass http://attendance-service;
        }
    }
}
